# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Part.create ([
  { :name => nil, :sku => nil, :tool_id => nil, :price => nil, :po => nil, :repair_id => nil, :service_id => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )



Repair.create([
  { :name => "replace on/off switch", :start_date => nil, :end_date => nil, :tool_id => 2, :created_at => "2013-06-04 06:02:20", :updated_at => "2013-06-07 00:54:52" },
  { :name => "test2", :start_date => "2013-08-08", :end_date => "2013-09-04", :tool_id => 3, :created_at => "2013-01-06 00:00:00", :updated_at => "2013-06-19 00:09:21" },
  { :name => "Replace bar", :start_date => "2013-06-13", :end_date => "2013-06-14", :tool_id => 3, :created_at => "2013-06-16 22:29:47", :updated_at => "2013-06-16 22:56:11" },
  { :name => "replace pull cord", :start_date => "2013-04-06", :end_date => "2013-04-06", :tool_id => 3, :created_at => "2013-06-04 06:04:42", :updated_at => "2013-06-04 06:04:42" },
  { :name => "test", :start_date => "2013-02-06", :end_date => "2013-07-09", :tool_id => 2, :created_at => "2013-01-06 00:00:00", :updated_at => "2013-06-15 06:08:57" },
  { :name => "test2", :start_date => "2013-01-06", :end_date => "2013-01-06", :tool_id => 2, :created_at => "2013-01-06 00:00:00", :updated_at => "2013-01-06 00:00:00" }
], :without_protection => true )



Role.create([
  { :name => "admin", :title => "role for admin", :description => "this user can do anything", :the_role => "{\"system\":{\"administrator\":true}}", :created_at => "2013-06-02 20:39:03", :updated_at => "2013-06-02 20:39:03" },
  { :name => "unconfirmed_user", :title => "Unconfirmed", :description => "Unconfirmed user", :the_role => "{\"login\":{\"denied\":true}}", :created_at => "2013-06-15 04:26:34", :updated_at => "2013-06-15 05:29:18" },
  { :name => "user", :title => "User", :description => "can CRUD records", :the_role => "{\"tools\":{\"index\":true,\"show\":true,\"create\":true,\"edit\":true,\"update\":true,\"destroy\":false},\"repairs\":{\"index\":true,\"show\":true,\"create\":true,\"edit\":true,\"update\":true,\"destroy\":true,\"new\":true},\"service\":{\"index\":true,\"show\":true,\"create\":true,\"edit\":true,\"update\":true,\"destroy\":true,\"new\":true},\"parts\":{\"index\":true,\"show\":true,\"create\":true,\"edit\":true,\"update\":true,\"destroy\":true,\"new\":true},\"reports\":{\"index\":true,\"show\":true,\"create\":true,\"edit\":true,\"update\":true,\"destroy\":true,\"new\":false},\"user\":{\"index\":true,\"show\":true,\"edit\":true,\"update\":true,\"destroy\":false}}", :created_at => "2013-06-03 17:30:32", :updated_at => "2013-06-15 06:37:35" }
], :without_protection => true )



Service.create([
  { :name => "oil change", :due_date => "2013-10-06", :completed => nil, :tool_id => 4, :created_at => "2013-01-06 00:00:00", :updated_at => "2013-03-06 00:00:00" },
  { :name => "oil change", :due_date => "2013-06-17", :completed => "2013-06-18", :tool_id => 3, :created_at => "2013-01-06 00:00:00", :updated_at => "2013-06-18 18:21:58" },
  { :name => "Today's service", :due_date => "2013-06-16", :completed => "2013-06-16", :tool_id => 3, :created_at => "2013-06-16 22:48:58", :updated_at => "2013-06-16 22:53:31" },
  { :name => "Change Oil", :due_date => "2013-06-04", :completed => "2013-06-14", :tool_id => 2, :created_at => "2013-06-04 06:57:06", :updated_at => "2013-06-05 03:22:01" },
  { :name => "air filter", :due_date => "2013-01-06", :completed => "2013-06-06", :tool_id => 3, :created_at => "2013-06-04 06:30:17", :updated_at => "2013-06-16 22:38:12" },
  { :name => "spark plug", :due_date => "2012-06-10", :completed => "2013-06-10", :tool_id => 2, :created_at => "2013-06-04 05:52:14", :updated_at => "2013-06-04 05:52:14" }
], :without_protection => true )



Tool.create([
  { :name => "Chainsaw", :serial => "88493848488", :location => "E71", :purchased => "2013-04-03", :put_in_service => "2013-05-12", :cost => 500.0, :value => 500.0, :in_service => true, :retired => nil, :created_at => "2013-06-03 04:26:38", :updated_at => "2013-06-03 04:26:38", :note => nil, :condition => 10 },
  { :name => "Chainsaw", :serial => "99039393838", :location => "E73", :purchased => "2012-06-01", :put_in_service => "2012-07-03", :cost => 500.0, :value => 400.0, :in_service => true, :retired => nil, :created_at => "2013-06-03 04:52:27", :updated_at => "2013-06-03 04:52:27", :note => nil, :condition => 9 },
  { :name => "Chainsaw", :serial => "99990000", :location => "E78", :purchased => "2013-01-06", :put_in_service => "2013-02-03", :cost => 500.0, :value => 500.0, :in_service => false, :retired => nil, :created_at => "2013-06-03 05:01:35", :updated_at => "2013-06-03 05:01:35", :note => nil, :condition => 8 },
  { :name => "Circ. Saw", :serial => "03399383", :location => "L74", :purchased => "2012-10-03", :put_in_service => "2012-10-26", :cost => 800.0, :value => 800.0, :in_service => true, :retired => nil, :created_at => "2013-06-03 05:14:12", :updated_at => "2013-06-03 05:14:12", :note => nil, :condition => 7 },
  { :name => "Circ. Saw", :serial => "22828288383", :location => "E71", :purchased => "2013-06-03", :put_in_service => "2013-06-03", :cost => 800.0, :value => 800.0, :in_service => true, :retired => nil, :created_at => "2013-06-03 05:16:27", :updated_at => "2013-06-03 05:16:27", :note => nil, :condition => 8 },
  { :name => "Generator", :serial => "44494949494", :location => "E71", :purchased => "2010-04-10", :put_in_service => "2010-05-01", :cost => 1300.0, :value => 1000.0, :in_service => true, :retired => nil, :created_at => "2013-06-03 05:19:05", :updated_at => "2013-06-03 05:19:05", :note => nil, :condition => 9 },
  { :name => "Generator", :serial => "8494848493", :location => "E74", :purchased => "2013-06-03", :put_in_service => "2013-06-03", :cost => 1300.0, :value => 1300.0, :in_service => true, :retired => nil, :created_at => "2013-06-03 05:26:06", :updated_at => "2013-06-07 16:12:13", :note => "", :condition => 10 },
  { :name => "generator", :serial => "88888888888", :location => "E73", :purchased => "2013-06-03", :put_in_service => "2013-06-03", :cost => 1300.0, :value => 1300.0, :in_service => true, :retired => nil, :created_at => "2013-06-03 05:29:53", :updated_at => "2013-06-07 16:10:57", :note => "", :condition => 7 },
  { :name => "Not retired chainsaw", :serial => "66666666666", :location => "E79", :purchased => "2013-01-09", :put_in_service => "2013-06-06", :cost => 500.0, :value => 500.0, :in_service => true, :retired => nil, :created_at => "2013-06-06 17:08:12", :updated_at => "2013-06-06 17:22:29", :note => "Retired field should be blank!!", :condition => 10 },
  { :name => "blower", :serial => "000333333", :location => "E76", :purchased => "2013-07-06", :put_in_service => "2013-11-06", :cost => 500.0, :value => 500.0, :in_service => true, :retired => nil, :created_at => "2013-06-07 17:08:59", :updated_at => "2013-06-07 17:08:59", :note => "", :condition => 5 },
  { :name => "Date-picker!", :serial => "292929292929", :location => "E74", :purchased => "2013-04-06", :put_in_service => "2013-09-06", :cost => 500.0, :value => 500.0, :in_service => true, :retired => nil, :created_at => "2013-06-09 20:08:42", :updated_at => "2013-06-09 20:08:42", :note => "", :condition => 5 },
  { :name => "Blower", :serial => "8847473663", :location => "E77", :purchased => "2013-06-01", :put_in_service => "2013-06-02", :cost => 900.0, :value => 800.0, :in_service => true, :retired => nil, :created_at => "2013-06-02 21:04:31", :updated_at => "2013-06-15 06:27:59", :note => "Purchased under \"Idle Reduction\" grant. ", :condition => 5 },
  { :name => "datepicker", :serial => "9999999999999999", :location => "A74", :purchased => "2013-10-06", :put_in_service => "2013-10-20", :cost => 500.0, :value => 500.0, :in_service => true, :retired => nil, :created_at => "2013-06-16 22:32:24", :updated_at => "2013-06-16 22:33:04", :note => "datepicker not working?", :condition => 5 }
], :without_protection => true )



User.create([
  { :username => "andy", :email => "andy@example.com", :crypted_password => "$2a$10$JEhk5Dc06IUS6NWxWukfMuX43UKvSdkGQovpGx9Fdeap1ZxeBf/oq", :salt => "vhTsjYAFy349WBzwRCW8", :created_at => "2013-06-02 18:19:06", :updated_at => "2013-06-02 20:45:22", :role_id => 1 },
  { :username => "Jeff", :email => "jzigler@kentfirerfa.org", :crypted_password => "$2a$10$EI2CSjZJZqorKe1bbGaUCeXfEvNekGjgs6Xf8QODQzVBiVVdUU1Ha", :salt => "nkJWxasQyzRfncSpqe9g", :created_at => "2013-06-10 00:59:08", :updated_at => "2013-06-10 00:59:08", :role_id => 2 },
  { :username => "Brian", :email => "bdodge@kentfirerfa.org", :crypted_password => "$2a$10$a16Qj.X1nfFKB026wnq8zu.FjB1UZwAarodhl.0NeE.GmYeIwWdIu", :salt => "KithHkonqqpNDMHWWzBs", :created_at => "2013-06-15 06:48:38", :updated_at => "2013-06-15 06:48:38", :role_id => 2 }
], :without_protection => true )


